name: Pipeline CI-CD Evaluacion 2

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main

jobs:
  calidad-y-seguridad:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout de codigo
        uses: actions/checkout@v3

      - name: Configurar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Instalar dependencias
        run: |
          npm install || echo "No hay dependencias"

      - name: Ejecutar pruebas unitarias
        run: |
          npm test

      - name: Escaneo de Seguridad (Snyk)
        uses: snyk/actions/node@master
        continue-on-error: true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

      - name: Construir imagen Docker
        run: |
          docker build -t mi-microservicio:latest .